# Generated by Django 4.0.4 on 2022-05-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('field_of_interest', models.CharField(max_length=500)),
            ],
        ),
    ]
