# Generated by Django 4.0.4 on 2022-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistsubscribers',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
