# Generated by Django 4.0.4 on 2022-09-13 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import v1.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=v1.utils.courses_image_path, verbose_name='Content icon')),
                ('underlay', models.ImageField(blank=True, null=True, upload_to=v1.utils.courses_image_path, verbose_name='Background Image')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('platform', models.CharField(max_length=200, verbose_name='Platform')),
                ('time_posted', models.DateTimeField(auto_now=True, verbose_name='Time posted')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Cost in dollar')),
                ('type', models.CharField(choices=[('remote', 'remote')], max_length=200, verbose_name='Employment type')),
                ('period_start', models.DateTimeField(default='django.utils.timezone.now', verbose_name='Starting Period')),
                ('period_end', models.DateTimeField(verbose_name='Ending Period')),
                ('about', models.TextField(blank=True, help_text='This field use markdown', null=True, verbose_name='About course')),
                ('experience', models.TextField(blank=True, help_text='This field use markdown', null=True, verbose_name='What you will learn')),
                ('skills', models.TextField(blank=True, help_text='This field use markdown', null=True, verbose_name='Skills you will gain')),
                ('visitors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='waitlistsubscribers',
            options={'verbose_name_plural': "Waitlist subscribers's"},
        ),
        migrations.AlterField(
            model_name='waitlistsubscribers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='waitlistsubscribers',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=v1.utils.opportunities_image_path, verbose_name='Content icon')),
                ('underlay', models.ImageField(blank=True, null=True, upload_to=v1.utils.opportunities_image_path, verbose_name='Background Image')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('time_posted', models.DateTimeField(auto_now=True, verbose_name='Time posted')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='Point')),
                ('type', models.CharField(choices=[('remote', 'remote')], max_length=200, verbose_name='Employment type')),
                ('period_start', models.DateTimeField(default='django.utils.timezone.now', verbose_name='Starting Period')),
                ('period_end', models.DateTimeField(verbose_name='Ending Period')),
                ('about', models.TextField(blank=True, help_text='This field use markdown', null=True, verbose_name='About course')),
                ('visitors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('age', models.CharField(blank=True, choices=[('Young', '18 - 25'), ('Youth', '25 - 50'), ('Old', '50 - Above')], max_length=10, null=True, verbose_name='Age Range')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('country_state', models.CharField(max_length=100, verbose_name='State')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Home Address')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('channel', models.CharField(blank=True, max_length=300, null=True, verbose_name='How did you hear about Sparkforce')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=1, validators=[v1.utils.validate_rate], verbose_name='Number of rating')),
                ('learning_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.learningcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('token', models.CharField(max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
