# Generated by Django 4.0.4 on 2022-09-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_learningcontent_alter_waitlistsubscribers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='type',
            field=models.CharField(default='auth', max_length=50),
            preserve_default=False,
        ),
    ]
