# Generated by Django 4.0.4 on 2022-09-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_otp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Author Name'),
        ),
    ]
