# Generated by Django 4.0.4 on 2022-08-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_waitlistsubscribers_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistsubscribers',
            options={'verbose_name_plural': "Waitlist subscribers's"},
        ),
    ]
