# Generated by Django 4.0.4 on 2022-09-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='link',
            field=models.CharField(default='changelater.com', max_length=500, verbose_name='Course Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='link',
            field=models.CharField(default='changelater.com', max_length=500, verbose_name='Opportunity Link'),
            preserve_default=False,
        ),
    ]
