# Generated by Django 4.0.4 on 2022-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='age',
            field=models.CharField(choices=[('Young', '18 - 25'), ('Youth', '25 - 50'), ('Old', '50 - Above')], default='18 - 25', max_length=10, verbose_name='Age Range'),
            preserve_default=False,
        ),
    ]
