# Generated by Django 4.0.4 on 2022-09-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_learningcontent_link_volunteeropportunity_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontent',
            name='link',
            field=models.CharField(help_text='Provide the absolute link (i.e must start with http:// or https://)', max_length=500, verbose_name='Course Link'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='link',
            field=models.CharField(help_text='Provide the absolute link (i.e must start with http:// or https://)', max_length=500, verbose_name='Opportunity Link'),
        ),
    ]
