# Generated by Django 4.0.4 on 2022-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_userinformation_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
