# Generated by Django 4.0.4 on 2022-08-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_alter_userinformation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='age',
            field=models.CharField(blank=True, choices=[('Young', '18 - 25'), ('Youth', '25 - 50'), ('Old', '50 - Above')], max_length=10, null=True, verbose_name='Age Range'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='channel',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='How did you hear about Sparkforce'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
