# Generated by Django 4.0.4 on 2022-08-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_alter_userinformation_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='state',
            new_name='country_state',
        ),
    ]
