# Generated by Django 4.0.4 on 2022-08-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0010_rename_state_userinformation_country_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='v1/images/', verbose_name='Content icon')),
                ('underlay', models.ImageField(upload_to='v1/images/', verbose_name='Content icon')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('platform', models.CharField(max_length=200, verbose_name='Platform')),
                ('time_posted', models.DateTimeField(auto_now=True, verbose_name='Time posted')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Cost in dollar')),
                ('type', models.CharField(choices=[('remote', 'remote')], max_length=200, verbose_name='Employment type')),
                ('period', models.DateTimeField(verbose_name='Period')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About course')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='What you will learn')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Skills you will gain')),
                ('visitors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=1, validators=[v1.models.validate_rate], verbose_name='Number of rating')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.learningcontent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
