# Generated by Django 4.0.4 on 2022-08-30 16:10

from django.db import migrations, models
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_alter_learningcontent_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontent',
            name='icon',
            field=models.ImageField(upload_to=v1.models.courses_image_path, verbose_name='Content icon'),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='underlay',
            field=models.ImageField(upload_to=v1.models.courses_image_path, verbose_name='Background Image'),
        ),
    ]
