# Generated by Django 4.0.4 on 2022-08-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_alter_learningcontent_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='course',
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='ratings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.rating'),
        ),
    ]
