# Generated by Django 4.0.4 on 2022-09-10 10:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import v1.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0015_remove_learningcontent_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontent',
            name='period',
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='period_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 10, 35, 24, 870644, tzinfo=utc), verbose_name='Ending Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='period_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 10, 35, 30, 684122, tzinfo=utc), verbose_name='Starting Period'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=v1.utils.courses_image_path, verbose_name='Content icon'),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='underlay',
            field=models.ImageField(blank=True, null=True, upload_to=v1.utils.courses_image_path, verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=v1.utils.courses_image_path, verbose_name='Content icon')),
                ('underlay', models.ImageField(blank=True, null=True, upload_to=v1.utils.courses_image_path, verbose_name='Background Image')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='Point')),
                ('type', models.CharField(choices=[('remote', 'remote')], max_length=200, verbose_name='Employment type')),
                ('period_start', models.DateTimeField(auto_now_add=True, verbose_name='Starting Period')),
                ('period_end', models.DateTimeField(verbose_name='Ending Period')),
                ('about', models.TextField(blank=True, help_text='This field use markdown', null=True, verbose_name='About course')),
                ('visitors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
