# Generated by Django 4.0.4 on 2022-09-10 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_remove_learningcontent_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='period_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 10, 41, 2, 245013, tzinfo=utc), verbose_name='Starting Period'),
        ),
    ]
