# Generated by Django 4.0.4 on 2022-09-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_alter_volunteeropportunity_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='period_start',
            field=models.DateTimeField(default='django.utils.timezone.now', verbose_name='Starting Period'),
        ),
    ]
