# Generated by Django 4.0.4 on 2022-09-10 10:46

from django.db import migrations, models
import v1.utils


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_alter_volunteeropportunity_period_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontent',
            name='period_start',
            field=models.DateTimeField(default='django.utils.timezone.now', verbose_name='Starting Period'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=v1.utils.opportunities_image_path, verbose_name='Content icon'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='underlay',
            field=models.ImageField(blank=True, null=True, upload_to=v1.utils.opportunities_image_path, verbose_name='Background Image'),
        ),
    ]
