# Generated by Django 4.0.4 on 2022-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0019_alter_learningcontent_period_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='time_posted',
            field=models.DateTimeField(auto_now=True, verbose_name='Time posted'),
        ),
    ]
